#!/usr/bin/env bash
# =============================================================================
# ClawFeeder Agent - Build Script
# =============================================================================
# Bakes build-time config into the binary via PyInstaller.
#
# Usage:
#   cp config.build.yaml.example config.build.yaml
#   # Edit config.build.yaml with your base_url
#   bash build.sh
#
# Output: dist/clawfeeder-agent
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_CONFIG="${SCRIPT_DIR}/config.build.yaml"
GENERATED="${SCRIPT_DIR}/src/_build_config.py"
VENV_PYTHON="${SCRIPT_DIR}/.venv/bin/python"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# ── Checks ────────────────────────────────────────────────────────────────────
if [[ ! -f "$VENV_PYTHON" ]]; then
  echo -e "${RED}[ERROR]${NC} Virtual environment not found."
  echo "  Run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt -r requirements.build.txt"
  exit 1
fi

if [[ ! -f "$BUILD_CONFIG" ]]; then
  echo -e "${RED}[ERROR]${NC} config.build.yaml not found."
  echo "  Run: cp config.build.yaml.example config.build.yaml"
  exit 1
fi

if grep -q '__BASE_URL__' "$BUILD_CONFIG"; then
  echo -e "${RED}[ERROR]${NC} config.build.yaml still contains placeholder '__BASE_URL__'."
  exit 1
fi

# ── Read build config ─────────────────────────────────────────────────────────
BASE_URL=$("$VENV_PYTHON" -c \
  "import yaml; d=yaml.safe_load(open('${BUILD_CONFIG}')); print(d['api']['base_url'])")
HEARTBEAT_INTERVAL=$("$VENV_PYTHON" -c \
  "import yaml; d=yaml.safe_load(open('${BUILD_CONFIG}')); print(d['api'].get('heartbeat_interval', 60))")

echo "[INFO] base_url: ${BASE_URL}"
echo "[INFO] heartbeat_interval: ${HEARTBEAT_INTERVAL}"

# ── Generate _build_config.py ─────────────────────────────────────────────────
cat > "$GENERATED" << PYEOF
# Auto-generated by build.sh — do not edit or commit.
BASE_URL = "${BASE_URL}"
HEARTBEAT_INTERVAL = ${HEARTBEAT_INTERVAL}
PYEOF

echo "[INFO] Generated src/_build_config.py"

# ── PyInstaller ───────────────────────────────────────────────────────────────
cd "$SCRIPT_DIR"
"$VENV_PYTHON" -m PyInstaller \
  --onefile \
  --name clawfeeder-agent \
  --clean \
  src/main.py

# ── Cleanup ───────────────────────────────────────────────────────────────────
rm -f "$GENERATED"
echo "[INFO] Cleaned up src/_build_config.py"

echo ""
echo -e "${GREEN}[OK]${NC} Built: ${SCRIPT_DIR}/dist/clawfeeder-agent"
echo ""
echo "Distribute dist/clawfeeder-agent to users, then run:"
echo "  bash install.sh"
