import json
import os
from pathlib import Path
from typing import List, Dict, Optional

class Storage:
    def __init__(self, data_dir: Path, expired_dir: Path):
        self.data_dir = data_dir
        self.expired_dir = expired_dir
        self._ensure_dirs()

    def _ensure_dirs(self):
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.expired_dir.mkdir(parents=True, exist_ok=True)

    def save_cookies(self, domain: str, data: dict):
        """Save decrypted cookies to local files"""
        cookies = data.get("cookies", [])

        # Save structured format (JSON)
        json_path = self.data_dir / f"{domain}.json"
        with open(json_path, 'w') as f:
            json.dump(data, f, indent=2)

        # Save Netscape format (for curl, wget, etc.)
        netscape_path = self.data_dir / f"{domain}.txt"
        with open(netscape_path, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by ClawFeeder. Do not edit.\n\n")
            for c in cookies:
                # Netscape format: domain tailmatch path secure expires name value
                # Use domain with leading dot for subdomains
                cookie_domain = c.get("domain", domain)
                if not cookie_domain.startswith("."):
                    cookie_domain = "." + cookie_domain
                path = c.get("path", "/")
                secure = "TRUE" if c.get("secure", False) else "FALSE"
                expires = c.get("expires", 0)
                name = c.get("name", "")
                value = c.get("value", "")
                f.write(f"{cookie_domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

        print(f"[Storage] Saved cookies for {domain}")

    def load_cookies(self, domain: str) -> Optional[dict]:
        """Load cookies from local file"""
        file_path = self.data_dir / f"{domain}.json"
        if file_path.exists():
            with open(file_path, 'r') as f:
                return json.load(f)
        return None

    def delete_cookies(self, domain: str):
        """Delete cookies files (both JSON and header format)"""
        json_path = self.data_dir / f"{domain}.json"
        header_path = self.data_dir / f"{domain}.txt"
        if json_path.exists():
            json_path.unlink()
        if header_path.exists():
            header_path.unlink()
        print(f"[Storage] Deleted cookies for {domain}")

    def move_to_expired(self, domain: str):
        """Move cookies to expired directory"""
        json_src = self.data_dir / f"{domain}.json"
        header_src = self.data_dir / f"{domain}.txt"
        if json_src.exists():
            dest = self.expired_dir / f"{domain}.json"
            dest.parent.mkdir(parents=True, exist_ok=True)
            json_src.rename(dest)
        if header_src.exists():
            header_dest = self.expired_dir / f"{domain}.txt"
            header_dest.parent.mkdir(parents=True, exist_ok=True)
            header_src.rename(header_dest)
        print(f"[Storage] Moved {domain} to expired")

    def list_local_domains(self) -> List[str]:
        """List all domains with saved cookies"""
        return [f.stem for f in self.data_dir.glob("*.json")]

    async def garbage_collect(self, cloud_domains: List[str]):
        """
        Compare local files with cloud state and clean up:
        - Remove local files not in cloud
        - Move to expired if status='expired'
        """
        local_domains = set(self.list_local_domains())
        cloud_domains_set = set(cloud_domains)

        for domain in local_domains - cloud_domains_set:
            self.delete_cookies(domain)

        print(f"[Storage] GC completed: {len(local_domains)} local, {len(cloud_domains)} cloud")
